//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMHC.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AfricanMHCEntities : DbContext
    {
        public AfricanMHCEntities()
            : base("name=AfricanMHCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditTrail> AuditTrail { get; set; }
        public virtual DbSet<diseases> diseases { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<planttransactions> planttransactions { get; set; }
        public virtual DbSet<RequestAppointment> RequestAppointment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<AppUser> AppUser { get; set; }
        public virtual DbSet<ChatMessages> ChatMessages { get; set; }
        public virtual DbSet<diseasetransactions> diseasetransactions { get; set; }
        public virtual DbSet<FAQ> FAQ { get; set; }
        public virtual DbSet<MessagesHistory> MessagesHistory { get; set; }
        public virtual DbSet<plants> plants { get; set; }
    
        public virtual int AprioriDiseases()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AprioriDiseases");
        }
    
        public virtual int AprioriDiseases2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AprioriDiseases2");
        }
    
        public virtual int AprioriPlants()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AprioriPlants");
        }
    
        public virtual int AprioriPlants2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AprioriPlants2");
        }
    
        public virtual int ReadMessage(string recepient, ObjectParameter message, ObjectParameter sender)
        {
            var recepientParameter = recepient != null ?
                new ObjectParameter("recepient", recepient) :
                new ObjectParameter("recepient", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReadMessage", recepientParameter, message, sender);
        }
    }
}
