//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Surname { get; set; }
        public string Middlename { get; set; }
        public string Firstname { get; set; }
        public string DateOfBirth { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string Occupation { get; set; }
        public byte[] Picture { get; set; }
        public string Usertype { get; set; }
    }
}
