//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class diseasetransactions
    {
        public int sn { get; set; }
        public string transID { get; set; }
        public string disease { get; set; }
        public string plant { get; set; }
    }
}
