//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public decimal id { get; set; }
        public System.DateTime logindate { get; set; }
        public string sessionid { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> lastmessagetime { get; set; }
        public string useripaddress { get; set; }
        public Nullable<bool> loggedin { get; set; }
    }
}
