//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessagesHistory
    {
        public decimal id { get; set; }
        public string sender { get; set; }
        public string recepient { get; set; }
        public string message { get; set; }
        public System.DateTime senddate { get; set; }
        public Nullable<bool> delivered { get; set; }
        public Nullable<System.DateTime> recieveddate { get; set; }
    }
}
