//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMHC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class plants
    {
        public string PlantID { get; set; }
        public string Family { get; set; }
        public string Species { get; set; }
        public string Yoruba { get; set; }
        public string Hausa { get; set; }
        public string Igbo { get; set; }
        public string CommonName { get; set; }
        public string PartsUsed { get; set; }
        public string MedicinalUse { get; set; }
        public string Picture { get; set; }
        public string Price { get; set; }
    }
}
